create table if not exists public.a2a_crawler_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  domain text not null,
  contact text,
  message text,
  status text not null default 'pending',
  metadata jsonb
);

create index if not exists idx_a2a_crawler_submissions_created_desc
  on public.a2a_crawler_submissions (created_at desc, id desc);

