export const MESSAGE_TYPES = {
  PLAYER_JOIN: 'PLAYER_JOIN',
  PLAYER_ID: 'PLAYER_ID',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  GAME_STATE: 'GAME_STATE',
  PLAYER_MOVE: 'PLAYER_MOVE',
  PLAYER_ATTACK: 'PLAYER_ATTACK',
  PLAYER_KILL: 'PLAYER_KILL',
  PLAYER_LEAVE: 'PLAYER_LEAVE',
  FACTION_ASSIGNED: 'FACTION_ASSIGNED',
  ROUND_STATE: 'ROUND_STATE',
  ROUND_END: 'ROUND_END',
  GLOBAL_SCORE: 'GLOBAL_SCORE'
};
